### ISSUE TITLE
Help wanted to add a server.

### ISSUE THREAD

**Issue by redmine4404** [MatthewL246/pretendo-docker#101]
Hello, i want to add the mincraft server to the pretendo docker project, for now i'm only trying to run a minecraft server with my pretendo docker instance outside a docker environment, after configuring all the environments variable and adding the server to the different script i can start a connection with the server but game thrown me an 106-0102 error (nex error code : Core::Unknown)

The error is caused by a error when the Minecraft server try to communicate to the account server to recover the user password, in the console the Minecraft server says :
`http2 error : frame too large`, after a bit of digging with wireshark it seem that the account server is sending an http page with the phrase "bad request" or "a web socket request was expected". 

So I have two question ? 
How to debug it ? The account server is only displaying a few messages, I don't know how to get more log with it and  where to search to have an specific error message ?

Is it a generic errors ? Is it like a problem that happen often or there is a well known solution to fix that because I have done probably a thing a thing I shouldn't do. Or is it a very specific problem that only me has encounter and I have to figure out alone ?

I will really appreciate all the help I will receive. I don't want to waste anybody's time.

Best regards, redmine4404.

PS. Sorry for my bad English.

**Comment by MatthewL246** [comment]
Interesting. It sounds like there's some sort of an issue with the gRPC connection between the Minecraft and account servers, as that's the only thing that uses HTTP/2 as far as I know. There might be a configuration issue with how the Minecraft server gRPC environment variables are set up. I believe they should be set up like this.

```
PN_MINECRAFT_ACCOUNT_GRPC_HOST=account
PN_MINECRAFT_ACCOUNT_GRPC_PORT=5000
PN_MINECRAFT_ACCOUNT_GRPC_API_KEY=<same account gRPC API key as the other servers>
```

If the configuration is already fine, there might be some other issue with the server or your network environment. Checking in Wireshark was a good idea, and you can also use a Node.js debugger with the account server. There aren't currently any verbose options for server logging.

I'll look into this further when I add the Minecraft server.

**Comment by redmine4404** [comment]
i think that 
```
PN_MINECRAFT_ACCOUNT_GRPC_HOST=account
PN_MINECRAFT_ACCOUNT_GRPC_PORT=5000
```
are place holder value, because `account` isn't obviusly a ip address, and the port 5000 just send an connection refused, the account server listen the port 9229. But thanks for the recommendation with the node.js debugger.

**Comment by MatthewL246** [comment]
I think I understand why you're getting this error. I don't generally work with servers running outside Docker, so I don't expose the gRPC server to the host by default.

The issue is that port 9229 is for the Node.js debugger, not the gRPC server. These are different protocols, so trying to connect to the debugger as gRPC won't work. If you want to expose the gRPC server to the host so you can connect to it from another program running outside of Docker, change the [ports section of the account server](https://github.com/MatthewL246/pretendo-docker/blob/8b706d17cb5d15dac4fcffac39198467c273e02b/compose.yml#L251-L253) to this:

```
    ports:
      # Node.js debugger
      - 127.0.0.1:9229:9229
      # gRPC server
      - 127.0.0.1:5000:5000
```

Now, you should be able to connect to it by using the following Minecraft server configuration.

```
PN_MINECRAFT_ACCOUNT_GRPC_HOST=127.0.0.1
PN_MINECRAFT_ACCOUNT_GRPC_PORT=5000
```

Inside the Docker container, it's better to use `account` instead of an IP address as the host because Docker will resolve a container name to the container's IP. However, if you're running the server outside of Docker, this doesn't work, so using an IP is correct. Also, you are allowed to connect to a non-exposed port in one container from another container inside the same network, but not from a program running outside of Docker. In that case, it needs to be exposed.

**Comment by redmine4404** [comment]
You're right, after exposing the right port and change the .env file i can connect  to the minecraft server with multiple instance of cemu. I should have look into the compose.yml sooner.

 But unfortunately i have still one problem, my physical wii U can connect to the auth server (exposed at port 6008) but it never make a connection to the secure server (exposed at port 6009) or at least the connection never show up in the console.
Thanks for your help and your time.

**Comment by MatthewL246** [comment]
Glad that helped! For your other error, make sure that `PN_MINECRAFT_SECURE_SERVER_PORT` is set correctly. Otherwise, I'm not sure why this would happen. Checking Wireshark for UDP packets coming from the Wii U might help.

**Comment by redmine4404** [comment]
It was pretty obvious thanks.

**Comment by MatthewL246** [comment]
Sounds like this is resolved. You're welcome!
