### ISSUE TITLE
Can we make servers available outside the network?

### ISSUE THREAD

**Issue by Gabriel-Chevallier** [MatthewL246/pretendo-docker#123]
I tried to open the ports of my network to redirect port 8080 and 8081, when a Wii U tries to connect with Inkay by entering my public ip as host and port 8080, I can't see any request on mitmproxy. I would like to point out that everything works very well on the local network.

So I'm wondering if it's possible to host servers that can be connected outside the local network.

**Comment by MatthewL246** [comment]
It's definitely possible, but you need to modify the mitmproxy configuration to make it work. Connecting from outside your local network is disabled by default, as exposing an open proxy to the internet can be dangerous. I made [a comment in another issue](https://github.com/MatthewL246/pretendo-docker/issues/86#issuecomment-2206726764) explaining how to do this and add proxy authentication for safety reasons.

Since you didn't mention it in your comment, I'll also add that you need to add port forwarding rules on your router for TCP port `8080` for mitmproxy, as well as every one of the UDP ports for the games' authentication and secure servers (such as `6000` and `6001` for Friends).

**Comment by MatthewL246** [comment]
I'm going to assume this is solved due to the lack of updates. Feel free to reopen this if you're still having issues.
