### ISSUE TITLE
Error using patch-sssl-certificate.sh

### ISSUE THREAD

**Issue by Gabriel-Chevallier** [MatthewL246/pretendo-docker#124]
After copying **CACERT_NINTENDO_CA_G3.der** in the console-files directory and running the **patch-sssl-certificate.sh** script, I got this error:

```
Error: The script /c/Users/Gabriel/Desktop/Network/pretendo-docker/scripts/patch-sssl-certificate.sh exited unexpectedly because an error occurred.
  /c/Users/Gabriel/Desktop/Network/pretendo-docker/scripts/patch-sssl-certificate.sh: line 30, in main
    docker run -it --rm -v .:/app/certs sssl -g3 /app/certs/CACERT_NINTENDO_CA_G3.der -o /app/certs
docker run -it --rm -v .:/app/certs sssl -g3 /app/certs/CACERT_NINTENDO_CA_G3.der -o /app/certs: exited with code 1
```

**Comment by MatthewL246** [comment]
Please send the entire output of the script so I can see the error message that the SSSL-patching container gives. Thanks!

**Comment by MatthewL246** [comment]
Glad to hear it's working, but I'm not sure what the issue was. It should work on WSL, which I use myself.

Unfortunately, I have not experimented with setting up BOSS tasks, so I'm not sure how to get that working. I'd recommend using mitmproxy to check what route it uses and then looking through the BOSS server source code to see how it is attempting to find the file.
