### ISSUE TITLE
image on hub.docker.com ? 

### ISSUE THREAD

**Issue by darkuser89** [MatthewL246/pretendo-docker#170]
Can you upload a finished image to hub.docker.com so that it can be downloaded?

**Comment by MatthewL246** [comment]
Unfortunately, it's a bit more complicated than that. Since this is a Docker Compose project, it requires running a separate Docker container for each server, and each of them uses a different image. The various scripts included in this repo are also required for first-time server setup. While it would be possible to write a completely custom Dockerfile that adds all of the Pretendo servers and associated scripts to a single image, this would make it more difficult to develop on a single server at a time, increase the complexity of maintaining this project, and (subjectively) doesn't align with the best practices for using containers.

I should note that public images for the individual Pretendo servers already exist, such as the [account server image](https://github.com/PretendoNetwork/account/pkgs/container/account). I would like to allow using these pre-made images instead of requiring everyone to build them themselves because that is obviously a waste of time and resources for most non-developers. I have added this as a future task to my roadmap (#50). However, I don't currently use them because I'm not sure what the best way to keep them updated and in sync with the submodules is.

- Always using the latest image is problematic because this project tracks the dev branch of all repos, which is not stable and can have breaking changes at any time.
- The servers don't have stable release versions at this time, so using a `v1` isn't an option.
- Therefore, I think that pinning the image to a specific commit is the only option, but Dependabot doesn't support Docker Compose files: https://github.com/dependabot/dependabot-core/issues/390. Even if it did, this doesn't help with ensuring that the images stay in sync with the submodules.
