### ISSUE TITLE
[Question] Discord Support

### ISSUE THREAD

**Issue by Volcan4436** [MatthewL246/pretendo-docker#179]
Does this have support to send logs / crash data to a Discord Bot or a Discord WebHook?

**Comment by MatthewL246** [comment]
No, that isn't a feature of this project. Adding an easier way to report problems is on the roadmap (#50, see `Add an option to the scripts to dump the output to a temporary file for issue-reporting purposes...`), though it's planned to create a log file that can be uploaded to any service (like GitHub or Discord) instead of automatically uploading directly to a webhook.
