### ISSUE TITLE
Splatoon?

### ISSUE THREAD

**Issue by olavito** [MatthewL246/pretendo-docker#54]
Pretendo's splatoon server repo seems to have not been updated for a good year, and appears discontinued, but i'm not sure if there's a newer version of it somewhere. Is adding it feasible to the docker env?

**Comment by MatthewL246** [comment]
Running the Splatoon server is definitely a priority. Someone else has already attempted to add it to this environment in [their fork](https://github.com/akatsukilevi/pretendo/tree/feature/splatoon), although I believe it is a work in progress and haven't tested it myself. Regarding the lack of updates, I am not sure whether the Splatoon servers on GitHub are up-to-date with what the Pretendo developers are running in production. It is possible that the servers just haven't been updated in a year, but it is also possible that the new code hasn't been pushed to GitHub yet.

**Comment by olavito** [comment]
Seems the fork still has some work to be done. splatoon servers start up fine but i can't connect yet. spotpass required cuz of the receiving news thing
(might also be some server environment thing tho but i don't think that matters. i just can't connect to splatoon yet)

**Comment by olavito** [comment]
well i guess i'll close it since it's "solved". splatoon servers are planned and that's really what i wanted to know

**Comment by akatsukilevi** [comment]
> Seems the fork still has some work to be done. splatoon servers start up fine but i can't connect yet. spotpass required cuz of the receiving news thing (might also be some server environment thing tho but i don't think that matters. i just can't connect to splatoon yet)

Hey, I'm the one currently developing that fork
Atm, only splatoon-secure-auth is working, the actual game server seems to not be accepting requests(apparently I messed up some port forwarding on the docker compose file)

![image](https://github.com/MatthewL246/pretendo-docker/assets/37668033/31f3c0d9-56da-4dd0-8697-987a95771c2c)

I put a small pause at it at the moment since I ended up infected with a virus, and these last few days I've been.... barely alive lol
But once I'm fully recovered, I'll be coming back at full steam to get the Splatoon server up 'n running, maybe even able to sustain a proper match

**Comment by olavito** [comment]
Then I probably set up something wrong since not even auth got a connect

**Comment by akatsukilevi** [comment]
Eyo! So, just to report, I could re-start development onto this project
In a nutshell, I ended up having to step back due to my computer deciding to kill itself(everybody gangsta until your SATA controller throws DMA_WRITE_ERROR), me being banned from Pretendo(apparently the used Wii U I had bought had the files dumped onto internet and a bunch of ppl was using it... Just my luck. The staff is right to ban tho, at least it helped stop cheaters using hacked files) and general lack of motivation
Yet, decided to pick back on it and now resumed to re-implement Splatoon into it
My goal is to get it in a state anyone can get it up and host their own Splatoon servers

**Comment by MatthewL246** [comment]
@akatsukilevi Sorry to hear about the issues you've been having but it's great that you can work on this again! Quarky's recently updated the Splatoon server to [nex-go v2 here](https://github.com/ashquarky/splatoon) (which you might have already heard about from the most recent blog post), I think it would be best to start working on that instead of on the 2-year-old version.
