### ISSUE TITLE
How to access admin paner from difference service outside the host server

### ISSUE THREAD

**Issue by redmine4404** [MatthewL246/pretendo-docker#55]
I have setup my pretendo server in a laptop that i use as a server that doesnt have a video output (only CLI), but i want to know how i can access the different administration panel (MongoDB, mitdm) from my pc in my local pc (or a vpn) without exposing all port to the internet.
I have very basics knowledge of docker.

**Comment by redmine4404** [comment]
PS. Sorry for my bad english.

**Comment by MatthewL246** [comment]
You can edit `compose.yml` and, for the ports you want to access, replace `127.0.0.1` with your server's local IP address to expose them. For example, if you want to expose mitmproxy and your server IP is `192.168.1.2`, change

```yml
    ports:
      # Proxy server
      - 8080:8080
      # Mitmweb interface
      - 127.0.0.1:8081:8081
```

to

```yml
    ports:
      # Proxy server
      - 8080:8080
      # Mitmweb interface
      - 192.168.1.2:8081:8081
```

This should let you access the services from another computer on your local network. This shouldn't expose them to the entire internet because that should be blocked by your router's firewall. If the server isn't on your local network, you would need to try something like SSH tunneling.

**Comment by redmine4404** [comment]
Thanks, but i think i don't really understand, why do exposing the server local ip gonna make the container expose to my local network ?

**Comment by redmine4404** [comment]
I have change the 127.0.0.1 to my server ip and now i work, thanks. I still don't understand but thanks.
