### ISSUE TITLE
Alternate Patches

### ISSUE THREAD

**Issue by PiplupDevelopments** [MatthewL246/pretendo-docker#86]
hi, its me again. I was wondering if you can compile a patch for external users. I have my Wii U on the same LAN as my server and i want to have friends from WAN to join, but i cant seem to compile another patch on a different ip (the public ip). is this possible?

**Comment by MatthewL246** [comment]
Hi, it sounds like you're misunderstanding how the server redirection works. Inkay replaces URLs like `account.nintendo.net` with `account.pretendo.cc`, and the custom build of Inkay just changes the SSL certificate that it accepts. The part that actually redirects requests to your local server is the proxy, so you need your friends to connect to your proxy server. By default, mitmproxy blocks IPs outside your LAN for safety reasons because bad actors will abuse open proxies on the Internet to send spam and attacks.

You can disable this by editing the `command` line of `mitmproxy-pretendo` in `compose.yml`, add `--set block_global=false` to the end. I strongly recommend also setting a username and password for your proxy by adding `--set proxyauth="username:password"` (but choose a better username and password of course!) to prevent bad actors from abusing your proxy server. You'll just need to inform everyone else what the username and password need to be when they set up the proxy in the console's Internet settings.

**Comment by PiplupDevelopments** [comment]
once again, you save the day. Thank you so much, I am sorry for my lack of knowledge in this sort of thing, i'm just a cpp dev haha and I don't know much about these things.

**Comment by PiplupDevelopments** [comment]
Wait sorry I'm dumb, where is the command line for mitmproxy-pretendo? (ー_ーゞ

**Comment by MatthewL246** [comment]
No problem, it's on [this line](https://github.com/MatthewL246/pretendo-docker/blob/93df73baef94d57cc883323504408655fff3a4ab/compose.yml#L16).

**Comment by PiplupDevelopments** [comment]
ah alright thanks again haha

**Comment by PiplupDevelopments** [comment]
YAYYY it works tysmm
